django_xunit_viewer/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('xunit_viewer.urls')),
]

xunit_viewer/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^project/(?P<project_id>[0-9]+)/$', views.project, name='project'),
    url(r'^test/(?P<test_result_id>[0-9]+)/$', views.test_result, name='test_result'),
]

xunit_viewer/models.py
from django.db import models


class Project(models.Model):
    name = models.CharField(max_length=50, unique=True)
    xunit_output_path = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class TestResult(models.Model):
    project = models.ForeignKey(Project)
    xml_file = models.TextField()
    json_results = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} {}'.format(self.project.name, self.date)

    class Meta:
        ordering = ('date',)

xunit_viewer/views.py
from django.shortcuts import get_object_or_404, render
import json
from lxml import etree

from .models import Project, TestResult


def index(request):
    context = {'projects': Project.objects.all()}
    return render(request, 'xunit_viewer/index.html', context)


def project(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    context = {'project': project}
    return render(request, 'xunit_viewer/project.html', context)


def _compute_successful(d):
    return int(d.get('tests', 0)) - int(d.get('errors', 0)) \
        - int(d.get('failures', 0)) - int(d.get('skip', 0))

def _compute_json_results(test_result, validate=True):
    schema = etree.XMLSchema(etree.parse(open('junit-4_custom.xsd'))) \
             if validate else None
    parser = etree.XMLParser(schema=schema)
    testsuite = etree.fromstring(str(test_result.xml_file), parser)
    assert(testsuite.tag == 'testsuite')
    res = {
        'stats': {
            'total_tests': int(testsuite.attrib['tests']),
            'successful': _compute_successful(testsuite.attrib),
            'errors': int(testsuite.attrib['errors']),
            'failures': int(testsuite.attrib['failures']),
            'skipped': int(testsuite.attrib['skip']),
        },
        'tests': [],
    }

    for testcase in testsuite:
        assert(testcase.tag == 'testcase')
        _res = {
            'class_name': testcase.attrib['classname'],
            'name': testcase.attrib['name'],
            'time': testcase.attrib['time'],
            'result': 'success',
        }
        for node in testcase:
            if node.tag in ('error', 'failure'):
                _res['result'] = node.tag
                _res['error_type'] = node.attrib['type']
                _res['error_message'] = node.attrib['message']
                _res['error_data'] = node.text
            elif node.tag in ('system-out', 'system-err'):
                _res['error_message'] = node.text  # FIXME: not error_message!!!
            res['tests'].append(_res)

    test_result.json_results = json.dumps(res)
    test_result.save()
    return res


def test_result(request, test_result_id):
    test_result = get_object_or_404(TestResult, pk=test_result_id)
    # if test_result.json_results is None or not test_result.json_results:
    json = _compute_json_results(test_result)
    context = {'test_result': test_result,
               'results': json}
    return render(request, 'xunit_viewer/test_result.html', context)

xunit_viewer/templates/xunit_viewer/base.html
{% load staticfiles %}<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>xunit viewer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'xunit_viewer/css/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'xunit_viewer/css/skeleton.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'xunit_viewer/css/style.css' %}">
    <link rel="icon" type="image/png" href="{% static 'xunit_viewer/images/favicon.png' %}">
  </head>
  <body>
    {% block content %}{% endblock content %}
    <script src="{% static 'xunit_viewer/js/jquery-2.1.4.min.js' %}"></script>
    {% block js_post %}
    {% endblock js_post %}
  </body>
</html>

xunit_viewer/templates/xunit_viewer/index.html
{% extends "xunit_viewer/base.html" %}

{% block content %}

{% if projects %}
Projects:
<ul>
  {% for project in projects %}
  <li><a href="{% url 'project' project.pk %}">{{ project.name }}</a></li>
  {% endfor %}
</ul>
{% else %}
<p>No projects!</p>
{% endif %}

{% endblock content %}

xunit_viewer/templates/xunit_viewer/project.html
{% extends "xunit_viewer/base.html" %}

{% block content %}

<h1>{{ project.name }}</h1>

<h2>Recent tests:</h2>
{% if project.testresult_set.all %}
<ul>
  {% for test in project.testresult_set.all %}
  <li><a href="{% url 'test_result' test.pk %}">{{ test.date | timesince }} ago</a></li>
  {% endfor %}
{% else %}
<p>No test results registered yet!</p>
{% endif %}

{% endblock content %}

xunit_viewer/templates/xunit_viewer/test_result.html
{% extends "xunit_viewer/base.html" %}

{% load staticfiles %}

{% block content %}

<div class="container">
  <h1>{{ test_result.project.name }} @ {{ test_result.date }}</h1>
  <canvas id="pie_chart" width="80" height="80"></canvas>
  <p>debug: {{ results.stats.tests }} reported vs {{ results.tests | length }} tests in list!</p>

  {% for r in results.tests %}
  <h6 class="title">{{ r.name }}</h6>
  <div class="indent">
    <p>class: <code>{{ r.class_name }}</code></p>
    <p>time: {{ r.time }}s</p>

    {% if r.error_message %}
    <div class="code_header_container">
      <div class="code_header">Error Message</div>
      <code class="block_scroll">{{ r.error_message | linebreaksbr }}</code>
    </div>
    {% endif %}

    {% if r.error_message %}
    <div class="code_header_container">
      <div class="code_header">Error Data</div>
      <code class="block_scroll">{{ r.error_data | linebreaksbr }}</code>
    </div>
    {% endif %}

  </div>
  {% endfor %}

</div>
{% endblock content %}

{% block js_post %}
<script src="{% static 'xunit_viewer/js/Chart.min.js' %}"></script>
<script>
stats = {{ results.stats | safe }};
</script>
<script src="{% static 'xunit_viewer/js/test_results.js' %}"></script>
{% endblock %}